name: Windows x64 Build with Python 3.11

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nuitka Build x64 (Windows)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          standalone: true
          enable-plugins: tk-inter
          disable-console: true
          output-dir: build

      - name: Rename Artifact
        run: |
          mkdir build || echo "build folder exists"
          move build\main.exe build\PTZ-Control-System.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: build/PTZ-Control-System.exe
